apiVersion: batch/v1
kind: Job
metadata:
  name: simplemail-worker-migrate
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      name: simplemail-worker-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: worker-migrate
          image: simplemail:latest
          imagePullPolicy: IfNotPresent
          command: ["node", "dist/worker/migrate.js"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: simplemail-secrets
                  key: database_url
